create table public.pixels (
  id smallint generated by default as identity not null,
  is_sold boolean not null default false,
  user_email text null,
  color text not null default '#ffffff'::text,
  image_url text not null,
  link_url text not null,
  stripe_session_id text not null,
  constraint pixelearth_pkey primary key (id, color, image_url, link_url, stripe_session_id)
) TABLESPACE pg_default;

SELECT id, is_sold, color, image_url, link_url FROM pixels LIMIT 10;

-- créer le tableau de pixel
insert into pixels (id) 
select generate_series(0, 1599);


